version: '3.9'

services:
  mysql:
    image: mysql
    container_name: mysql
    networks:
      - app-network
    ports:
      - "33060:3306"
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=laura
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
networks:
  app-network:
volumes:
  mysql-data: