basePath: /products
host: localhost:8080
info:
  contact:
    name: API Support
    url: https://developers.com.ar/support
  description: This API Handle Products.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developers.com.ar/es_ar/terminos-y-condiciones
  title: API Go-Products
  version: "1.0"
paths:
  /products:
    get:
      consumes:
      - application/json
      description: Get all products
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: error
          schema:
            type: string
      summary: List products
      tags:
      - Products
swagger: "2.0"
